### ISSUE TITLE
Missing call-bind dependency

### ISSUE THREAD

**Issue by markandrus** [es-shims/DisposableStack#6]
Recent versions of Yarn (e.g., 4.2.2) detect that disposablestack attempts to access call-bind, but call-bind is not listed as a dependency. It fails as follows:

```
% yarn add disposablestack

% yarn node -e "require('disposablestack/auto')"
/private/tmp/.pnp.cjs:6414
    throw firstError;
    ^

Error: disposablestack tried to access call-bind, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: call-bind
Required by: disposablestack@npm:1.1.4 (via /Users/mark/.yarn/berry/cache/disposablestack-npm-1.1.4-cd1f88f9e7-10c0.zip/node_modules/disposablestack/DisposableStack/)

Require stack:
- /Users/mark/.yarn/berry/cache/disposablestack-npm-1.1.4-cd1f88f9e7-10c0.zip/node_modules/disposablestack/DisposableStack/implementation.js
- /Users/mark/.yarn/berry/cache/disposablestack-npm-1.1.4-cd1f88f9e7-10c0.zip/node_modules/disposablestack/DisposableStack/polyfill.js
- /Users/mark/.yarn/berry/cache/disposablestack-npm-1.1.4-cd1f88f9e7-10c0.zip/node_modules/disposablestack/DisposableStack/shim.js
- /Users/mark/.yarn/berry/cache/disposablestack-npm-1.1.4-cd1f88f9e7-10c0.zip/node_modules/disposablestack/shim.js
- /Users/mark/.yarn/berry/cache/disposablestack-npm-1.1.4-cd1f88f9e7-10c0.zip/node_modules/disposablestack/auto.js
- /private/tmp/[eval]
    at require$$0.Module._resolveFilename (/private/tmp/.pnp.cjs:6413:13)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at require$$0.Module._load (/private/tmp/.pnp.cjs:6304:31)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/mark/.yarn/berry/cache/disposablestack-npm-1.1.4-cd1f88f9e7-10c0.zip/node_modules/disposablestack/DisposableStack/implementation.js:17:16)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at require$$0.Module._extensions..js (/private/tmp/.pnp.cjs:6456:33)
    at Module.load (node:internal/modules/cjs/loader:1206:32)

Node.js v20.12.2
```

This can be worked around with a package extension

```
% cat .yarnrc.yml
packageExtensions:
  "disposablestack@*":
    dependencies:
      call-bind: "*"

% yarn install

% yarn node -e "require('disposablestack/auto')"
```

However, can we add call-bind to disposablestack's dependencies to avoid this?

**Comment by ljharb** [comment]
While this is a side effect of choices that yarn pnp has made (it should work perfectly fine when using a non-broken node_modules layout), absolutely the dep should be explicitly listed. I'll publish a patch for it shortly.

**Comment by markandrus** [comment]
Thanks!
